sissbruecker/linkding

- bookmarks/admin.py
- Fixes #4 
- Added Tags in the admin page
- Added searching and filter capabilities in the Bookmarks section in the admin page
> Enhanced the admin page

- bookmarks/models.py
- bookmarks/templates/bookmarks/bookmark_list.html
- bookmarks/templates/bookmarks/edit.html
- bookmarks/templates/bookmarks/form.html
- bookmarks/templates/bookmarks/index.html
- bookmarks/templates/bookmarks/new.html
- bookmarks/templatetags/bookmarks.py
- bookmarks/views/bookmarks.py
> #26 Return to same page after editing or deleting bookmark

- README.md
- bookmarks/services/importer.py
- bookmarks/services/parser.py
- bookmarks/views/settings.py
- requirements.prod.txt
- requirements.txt
- uwsgi.ini
> Implement custom netscape file parser

- bookmarks/models.py
- bookmarks/queries.py
- bookmarks/services/tags.py
- bookmarks/tests.py
- bookmarks/tests/test_tags_model.py
- bookmarks/tests/test_tags_service.py
- bookmarks/utils.py
> Make tag search and assignment case insensitive

- bookmarks/styles/base.scss
- bookmarks/styles/bookmarks.scss
- bookmarks/templates/bookmarks/bookmark_list.html
- bookmarks/templates/bookmarks/pagination.html
- bookmarks/templatetags/pagination.py
- bookmarks/tests/test_pagination_tag.py
> Add pagination

- bookmarks/services/tags.py
- bookmarks/tests/test_tags_service.py
- siteroot/settings/dev.py
> Fix duplicate tag error

- bookmarks/models.py
- bookmarks/tests/test_bookmarks_model.py
> Show URL as fallback if no title is available

- bookmarks/components/SearchAutoComplete.svelte
- bookmarks/styles/bookmarks.scss
- bookmarks/styles/shared.scss
- bookmarks/templates/bookmarks/index.html
- bookmarks/templates/bookmarks/layout.html
- bookmarks/templates/bookmarks/nav_menu.html
> Fix mobile issues with searchbox and nav menu

- bookmarks/api/routes.py
> Fix archive endpoints (#77)

- bookmarks/api/serializers.py
> Mark optional fields in bookmark serializer (#78)

- README.md
- docs/backup.md
Created a small document with some suggestions to backup the database
> Added backup document

- README.md
- bookmarks/components/TagAutocomplete.svelte
- bookmarks/components/api.js
- bookmarks/services/bookmarks.py
- bookmarks/static/bulk_edit.js
- bookmarks/static/shared.js
- bookmarks/styles/base.scss
- bookmarks/styles/bookmarks.scss
- bookmarks/styles/dark.scss
- bookmarks/styles/shared.scss
- bookmarks/styles/util.scss
- bookmarks/templates/bookmarks/archive.html
- bookmarks/templates/bookmarks/bookmark_list.html
- bookmarks/templates/bookmarks/bulk_edit/bar.html
- bookmarks/templates/bookmarks/bulk_edit/state.html
- bookmarks/templates/bookmarks/bulk_edit/toggle.html
- bookmarks/templates/bookmarks/edit.html
- bookmarks/templates/bookmarks/form.html
- bookmarks/templates/bookmarks/index.html
- bookmarks/templates/bookmarks/layout.html
- bookmarks/templates/bookmarks/new.html
- bookmarks/templatetags/bookmarks.py
- bookmarks/tests/test_bookmarks_service.py
- bookmarks/tests/test_bulk_edit_integration.py
- bookmarks/urls.py
- bookmarks/views/bookmarks.py
Implements a bulk edit mode in the bookmark and archive views. The mode allows to:
- Bulk archive / unarchive
- Bulk delete
- Bulk add tags
- Bulk remove tags
> Implement bulk edit

- bookmarks/styles/bookmarks.scss
- bookmarks/templates/bookmarks/form.html
> Allow editing of scraped values (#80)

- bookmarks/tests/test_utils.py
- bookmarks/utils.py
> Fix relative date formatting (#107)

- README.md
- docs/Admin.md
Started an Admin documentation page.
> Admin documentation

- bookmarks/services/importer.py
- bookmarks/tests/helpers.py
- bookmarks/tests/test_bookmark_validation.py
- bookmarks/tests/test_importer.py
- bookmarks/tests/test_settings_import_view.py
> Fix importer not validating bookmark models

- bookmarks/services/website_loader.py
This patchset fixes issue on scraping.
1. Avoid stall on scraping
2. Avoid chracter corruption of scraping some Japanese site
Sincrely,
Taku Izumi
Fixes #148
> Fixup scraping

- bookmarks/static/shared.js
Adds a keyboard shortcut for focusing the search input, by pressing `s`.
> Add global search shortcut

- .dockerignore
> exclude .git in docker container

- bookmarks/api/serializers.py
- bookmarks/models.py
- bookmarks/services/bookmarks.py
- bookmarks/tests/test_bookmarks_api.py
- bookmarks/tests/test_bookmarks_service.py
- bookmarks/tests/test_importer.py
- bookmarks/tests/test_tags_model.py
- bookmarks/views/bookmarks.py
> Ensure tag names do not contain spaces

- bookmarks/components/TagAutocomplete.svelte
> Scroll menu items into view when using keyboard

- bookmarks/components/TagAutocomplete.svelte
> Add whitespace after auto-completed tag

- bookmarks/static/shared.js
> Feature: Shortcut key for new bookmark

- README.md
- docs/Options.md
Use the name in the readme that archive.org use.
> Issue #187 clarify archive.org feature

- README.md
Fixes #245
[Rendered preview](https://github.com/m3nu/linkding/tree/add-pikapods#managed-hosting-options)
> Add to managed hosting options

- bookmarks/styles/settings.scss
- bookmarks/templates/settings/general.html
- bookmarks/tests/test_settings_general_view.py
- bookmarks/views/settings.py
Changes:
- Show latest version
- Add additional links
- Display as table
> Improve about section

- README.md
https://github.com/sissbruecker/linkding/issues/290
> Add bookmarklet to community

- bookmarks/models.py
- bookmarks/services/bookmarks.py
- bookmarks/templates/bookmarks/form.html
- bookmarks/tests/test_bookmark_edit_view.py
- bookmarks/tests/test_bookmarks_service.py
> Skip updating website metadata on edit unless URL has changed

- README.md
Linka is an open source project which provides a web app (also a PWA) for searching and opening bookmarks in linkding.
It has following key features:
- fulltext search
- multiple keywords
- substract / exclude mode
- open instantly
- pwa
closes #315
> Add project linka to community section in README

- bookmarks/middlewares.py
- bookmarks/tests/test_auth_proxy_support.py
- docs/Options.md
- siteroot/settings/base.py
- siteroot/settings/dev.py
> Add support for authentication proxies

- .env.sample
- bookmarks/management/commands/create_initial_superuser.py
- bookmarks/tests/test_create_initial_superuser_command.py
- bootstrap.sh
- docs/Options.md
> Add option to create initial superuser

- docs/how-to.md
- docs/linkding_shortcut.json
Simpler to import, one less variable to edit and custom tag(s)
> Improved Android HTTP Shortcuts doc

- bookmarks/admin.py
Removes the confirmation page when deleting all bookmarks from admin, which could fail in production when the number of deleted objects exceeds 1000.
Fixes #325 
Fixes #337
> Fix error when deleting all bookmarks in admin

- .gitignore
- rollup.config.js
- siteroot/settings/base.py
> Fix static file dir warning

- bookmarks/tests/test_settings_general_view.py
- bookmarks/views/settings.py
> Add error handling for checking latest version

- docs/how-to.md
- docs/linkding_shortcut.json
This simplifies tagging and also filters URL's shared from apps. Useful for apps that don't share clean URLs
Co-Authored-By: Roland Meyer <2445563+Waboodoo@users.noreply.github.com>
> Android HTTP shortcuts v3

- bookmarks/frontend/components/SearchAutoComplete.svelte
- bookmarks/templates/bookmarks/search.html
- bookmarks/templatetags/bookmarks.py
> Make search autocomplete respect link target setting

- bookmarks/frontend/behaviors/modal.js
- bookmarks/frontend/index.js
- bookmarks/styles/base.scss
- bookmarks/styles/bookmark-page.scss
- bookmarks/styles/spectre.scss
- bookmarks/templates/bookmarks/archive.html
- bookmarks/templates/bookmarks/index.html
- bookmarks/templates/bookmarks/search.html
- bookmarks/templates/bookmarks/shared.html
Adds a button that opens the tag cloud in a modal on smaller screens.
Closes https://github.com/sissbruecker/linkding/issues/180
> Add button to show tags on smaller screens

- bookmarks/styles/bookmark-page.scss
Fixes https://github.com/sissbruecker/linkding/issues/524
> Make code blocks in notes scrollable

- bookmarks/frontend/components/SearchAutoComplete.svelte
- bookmarks/models.py
- bookmarks/queries.py
- bookmarks/styles/base.scss
- bookmarks/styles/bookmark-page.scss
- bookmarks/styles/spectre.scss
- bookmarks/styles/theme-dark.scss
- bookmarks/templates/bookmarks/search.html
- bookmarks/templatetags/bookmarks.py
- bookmarks/tests/test_bookmark_search_form.py
- bookmarks/tests/test_bookmark_search_model.py
- bookmarks/tests/test_bookmark_search_tag.py
- bookmarks/tests/test_bookmarks_api.py
- bookmarks/tests/test_queries.py
- bookmarks/tests/test_user_select_tag.py
Allows to filter for shared or unshared bookmarks.
> Add filter for shared state

- bookmarks/templates/bookmarks/archive.html
- bookmarks/templates/bookmarks/index.html
- bookmarks/templates/bookmarks/shared.html
- bookmarks/tests/test_bookmark_archived_view.py
- bookmarks/tests/test_bookmark_index_view.py
- bookmarks/tests/test_bookmark_shared_view.py
Fixes https://github.com/sissbruecker/linkding/issues/536
> Fix bulk edit to respect searched tags

- bookmarks/api/routes.py
- bookmarks/api/serializers.py
- bookmarks/tests/test_bookmarks_api.py
- bookmarks/tests/test_bookmarks_api_permissions.py
- docs/API.md
Based on #458
Fixes https://github.com/sissbruecker/linkding/issues/457
> Add user profile endpoint

- README.md
Adding my iOS shortcut within the Community section
> Add iOS shortcut to community section

- bookmarks/admin.py
Fixes https://github.com/sissbruecker/linkding/issues/554
> Disable editing of search preferences in user admin

- bookmarks/feeds.py
- bookmarks/tests/test_feeds.py
Fixes https://github.com/sissbruecker/linkding/issues/552
> Sanitize RSS feed to remove control characters

- bookmarks/templates/settings/general.html
Adjust archive.org donation link due to broken link.
> Adjust archive.org donation link in general.html

- bookmarks/services/bookmarks.py
- bookmarks/tests/test_bookmarks_service.py
> Improve bulk tag performance

- README.md
- bookmarks/services/website_loader.py
- bookmarks/tests/test_bookmark_new_view.py
- bookmarks/tests/test_website_loader.py
- pytest.ini
- requirements.txt
As discussed in https://github.com/sissbruecker/linkding-extension/issues/59 you pointed out that the change should be made in this repo. This PR adds a test and the code to support that change. 
I also took the liberty of introducing pytest, because it's a much nicer experience for running tests when you're developing :).
> Support Open Graph description (and introduce pytest for better dev ux)

- README.md
Hi there, just wanted to share my way of hosting linkding. Thanks for the software!
> Add k8s setup to community section

- README.md
Hi. I'm the developer of [Linkdy](https://github.com/JGeek00/linkdy), a Linkding client created with Flutter. The application is still under development, and on a very early stage. The objective is to create a mobile and desktop client, with the same features that the web already has. I have added a new entry on the community section.
> Added a new Linkding client to community section

- bookmarks/templates/bookmarks/nav_menu.html
Fixes https://github.com/sissbruecker/linkding/issues/646
> Fix logout button

- bookmarks/api/serializers.py
- bookmarks/tests/helpers.py
- bookmarks/tests/test_bookmarks_api.py
- docs/API.md
Closes https://github.com/sissbruecker/linkding/issues/573
> Include web archive link in /api/bookmarks/

- bookmarks/feeds.py
- bookmarks/templates/settings/integrations.html
- bookmarks/tests/test_feeds.py
- bookmarks/tests/test_settings_integrations_view.py
- bookmarks/urls.py
- bookmarks/views/settings.py
Closes https://github.com/sissbruecker/linkding/issues/452
> Add RSS feeds for shared bookmarks

- bookmarks/api/routes.py
- bookmarks/e2e/e2e_test_bookmark_form.py
- bookmarks/styles/bookmark-form.scss
- bookmarks/templates/bookmarks/form.html
- bookmarks/tests/test_bookmarks_api.py
Shows which tags would automatically be added when creating a bookmark.
> Preview auto tags in bookmark form

- bookmarks/api/routes.py
- bookmarks/api/serializers.py
- bookmarks/tests/helpers.py
- bookmarks/tests/test_bookmarks_api.py
- docs/API.md
> Include favicons and thumbnails in REST API

- bookmarks/styles/settings.scss
- bookmarks/styles/spectre.scss
- bookmarks/templates/settings/general.html
Fixes https://github.com/sissbruecker/linkding/issues/742
> Fix overflow in settings page

- bookmarks/feeds.py
- bookmarks/templates/settings/integrations.html
- bookmarks/tests/test_feeds.py
Closes https://github.com/sissbruecker/linkding/issues/784
> Return bookmark tags in RSS feeds

- bookmarks/feeds.py
- bookmarks/templates/settings/integrations.html
- bookmarks/tests/test_feeds.py
Closes https://github.com/sissbruecker/linkding/issues/789
> Additional filter parameters for RSS feeds

- bookmarks/models.py
- bookmarks/tests/test_bookmarks_list_template.py
Fixes https://github.com/sissbruecker/linkding/issues/818
> Fix inconsistent tag order in bookmarks

- bookmarks/styles/theme-dark.css
- bookmarks/styles/theme/forms.css
Fixes https://github.com/sissbruecker/linkding/issues/857
> Fix select dropdown menu background in dark theme

- bookmarks/templates/bookmarks/nav_menu.html
Fixes https://github.com/sissbruecker/linkding/issues/964
> Fix nav menu closing on mousedown in Safari

- bookmarks/templates/bookmarks/head.html
- bookmarks/tests/test_bookmark_archived_view.py
- bookmarks/tests/test_bookmark_index_view.py
- bookmarks/tests/test_bookmark_shared_view.py
- bookmarks/views/bookmarks.py
> Add RSS link to shared bookmarks page

- docker/alpine.Dockerfile
- docker/default.Dockerfile
Fixes https://github.com/sissbruecker/linkding/issues/453
Fixes https://github.com/sissbruecker/linkding/issues/946
> Try limit uwsgi memory usage by configuring file descriptor limit

- bookmarks/api/serializers.py
- bookmarks/tests/test_bookmarks_api.py
Fixes https://github.com/sissbruecker/linkding/issues/885
> Return web archive fallback URL from REST API

- bookmarks/templates/bookmarks/nav_menu.html
Fixes https://github.com/sissbruecker/linkding/issues/950
> Fix auth proxy logout

- bookmarks/api/auth.py
- bookmarks/tests/test_auth_api.py
- siteroot/settings/base.py
Closes https://github.com/sissbruecker/linkding/issues/471
> Allow providing REST API authentication token with Bearer keyword

- docs/src/content/docs/community.md
add my telegram bot project to send bookmarks directly to Linkding.
> Add Telegram bot to community section

- bookmarks/api/routes.py
- bookmarks/api/serializers.py
- bookmarks/templates/bookmarks/details/assets.html
- bookmarks/tests/helpers.py
- bookmarks/tests/test_assets_service.py
- bookmarks/tests/test_bookmark_action_view.py
- bookmarks/tests/test_bookmark_asset_view.py
- bookmarks/tests/test_bookmark_assets.py
- bookmarks/tests/test_bookmark_assets_api.py
- bookmarks/tests/test_bookmark_details_modal.py
- bookmarks/tests/test_bookmarks_api.py
- bookmarks/urls.py
- bookmarks/views/bookmarks.py
- bookmarks/views/contexts.py
- docs/src/content/docs/api.md
- docs/src/content/docs/options.md
- siteroot/settings/base.py
- uwsgi.ini
Closes https://github.com/sissbruecker/linkding/issues/718
> Add bookmark assets API

- docs/astro.config.mjs
- docs/src/content/docs/auto-tagging.md
Closes https://github.com/sissbruecker/linkding/issues/938
> Add docs for auto tagging

- bookmarks/api/routes.py
Fixes https://github.com/sissbruecker/linkding/issues/1032
> Fix bookmark asset download endpoint

- bookmarks/services/auto_tagging.py
- bookmarks/tests/test_auto_tagging.py
- docs/src/content/docs/auto-tagging.md
Closes https://github.com/sissbruecker/linkding/issues/1038
> Allow auto tagging rules to match URL fragments

- bookmarks/templates/bookmarks/head.html
- bookmarks/templates/opensearch.xml
- bookmarks/tests/test_opensearch_view.py
- bookmarks/urls.py
- bookmarks/views/__init__.py
- bookmarks/views/opensearch.py
Hi,
I wanted to have an OpenSearch integration for Linkding and figured it's a useful feature not just for me. I am not a Python developer, please let me know if/how I can improve these changes.
I also didn't manage to run the automated tests, I hope the pipeline will do this for me now.
I found #403 and tried to integrate your feedback into my changes as well.
Thanks for your hard work!
> Add opensearch declaration

- bookmarks/models.py
- bookmarks/queries.py
- bookmarks/services/assets.py
- bookmarks/tests/test_assets_service.py
- bookmarks/tests/test_queries.py
- docs/src/content/docs/api.md
Closes https://github.com/sissbruecker/linkding/issues/940
> Add date filters for REST API

- bookmarks/tests/test_settings_export_view.py
- bookmarks/views/settings.py
Closes https://github.com/sissbruecker/linkding/issues/1047
> Add date and time to HTML export filename

- bookmarks/templates/bookmarks/read.html
Fixes https://github.com/sissbruecker/linkding/issues/1042
> Fix custom CSS not being used in reader mode

- bookmarks/api/routes.py
- bookmarks/api/serializers.py
- bookmarks/services/bundles.py
- bookmarks/tests/test_bundles_api.py
- bookmarks/tests/test_bundles_index_view.py
- bookmarks/tests/test_settings_export_view.py
- bookmarks/views/bundles.py
Fixes https://github.com/sissbruecker/linkding/issues/1109
> Update order when deleting bundle

- bookmarks/services/importer.py
- bookmarks/tests/test_importer.py
Fixes https://github.com/sissbruecker/linkding/issues/1143
> Ignore tags that exceed length limit during import

- bookmarks/frontend/behaviors/form.js
- bookmarks/templates/bookmarks/edit.html
- bookmarks/templates/bookmarks/new.html
- bookmarks/tests_e2e/e2e_test_new_bookmark_form.py
Closes https://github.com/sissbruecker/linkding/issues/1031
> Submit bookmark form with Ctrl/Cmd + Enter

- bookmarks/templates/bookmarks/bookmarklet.js
- bookmarks/templates/bookmarks/bookmarklet_clientside.js
- bookmarks/templates/settings/integrations.html
- docs/src/content/docs/troubleshooting.md
Closes https://github.com/sissbruecker/linkding/issues/118
> Add alternative bookmarklet that uses browser metadata
