sissbruecker/linkding

bootstrap.sh, uwsgi.ini
Hi,
in the current docker container UWSGI runs as root, while there is no need for that.
Instead of dropping privileges and running as user www-data from within docker (which would be preferred IMHO) I run chown on the db file, so that users can transparently upgrade existing setups.
=> Drop privileges instead of running as root

bookmarks/services/importer.py
Fixes for #18 
- Use a default value if attribute missing from tag
- Added default '0' for 'toread': This means `bookmark.unread` will default to false
- Added default '' for 'tags': No tags will be added by default 
- Added default 'current time(`datetime.now().timestamp()`)' for `date_added`
- Use system's timezone for the parsed timestamp: Earlier the parsed timestamp was not made timezone aware whereas the model's field was timezone aware. This caused a warning while inserting the bookmark into the database. Not sure if this actually caused any problems, I added it because I was able to find it :slightly_smiling_face:
=> Fix for Bookmarks Importer

bookmarks/services/bookmarks.py, bookmarks/styles/bookmarks.scss, bookmarks/templates/bookmarks/edit.html, bookmarks/templates/bookmarks/form.html, bookmarks/templates/bookmarks/new.html, bookmarks/templatetags/bookmarks.py, bookmarks/urls.py, bookmarks/views/api.py
=> #23 Prevent bookmark duplicates

bookmarks/templates/bookmarks/bookmark_list.html
https://web.dev/external-anchors-use-rel-noopener/
=> Add rel=noopener attribute to external links

.env.sample, README.md, docker-compose.yml
Added the docker-compose.yml file and some instructions. I wasn't sure about how much text needed to be repeated.
`docker-compose exec linkding python manage.py createsuperuser --username=joe --email=joe@example.com` allows people to run this command even if they changed the container name since `docker-compose exec` checks for the service name in `docker-compose.yml` and not the container name.
Tested with and without the `.env`  file
=> Docker compose support

.dockerignore, Dockerfile, requirements.prod.txt
Hey, I really liked the design of the bookmark manager, so I tried to check it out locally. 
I tried to deploy it and it seemed like a lot of intermediate steps going between python and node tooling. I stopped and then tried docker and saw that Docker was also like that. Instead of opening an issue and hoping it'd get tidied up at some point, I instead went ahead and streamlined the build process by modifying the Dockerfile!
Now it'll go through the intermediate steps to build the static files all while building the docker image. So deployment is just:
```bash
docker run -ti --restart always -p 9090:9090 -v $PWD/uwsgi.ini:/etc/linkding/uwsgi.ini --name linkding sissbruecker/linkding
```
As for the changes themselves, the Dockerfile now utilizes mutlistage builds. This both reduces final …
=> Multistage Dockerfile

bookmarks/queries.py, bookmarks/tests/test_queries.py
I tested this change to speed up tag search.
BR
Fixes #112
=> changed query on tag search for speedup related to issues #112 and #141

Dockerfile
I recently deployed linkding to an OpenShift environment which required updating the permisisons of the `/etc/linkding` folder to make them group-writable. As per the OpenShift documentation (https://docs.openshift.com/container-platform/4.8/openshift_images/create-images.html), containers on OpenShift do not run as root but as an arbitrary user which is a member of the `root` group:
```
For an image to support running as an arbitrary user, directories and files that are written to by
processes in the image must be owned by the root group and be read/writable by that group.
Files to be executed must also have group execute permissions.
```
Thank you for considering this pull request.
=> Support running on OpenShift as an arbitrary user

README.md
Just a small change to the README removing a duplication of the word "support."
=> remove duplicate word in README

bookmarks/admin.py
The Tag view in django admin has a calculated bookmark count column that is unsortable. This fixes it.
=> Make bookmarks count column in admin sortable

README.md
The search results injection extension from sissbruecker/linkding-extension#11 is ready. See https://github.com/Fivefold/linkding-injector
This PR adds a link to the README in the Community section.
=> Added link to community extension linkding-injector to README

uwsgi.ini
Handles requests with a larger block size than the default 4096
Fixes: #28
=> Increase buffer size

bootstrap.sh, docs/Options.md, uwsgi.ini
While Docker containers have their own IP address namespace and port collisions are impossible to achieve, other container solutions share one.
Podman, for example, runs all containers in a pod under one namespace, which results in every port only being allowed to be assigned once. Having a default port in the image that cannot be changed can cause collisions and incompabilities.
This change allows setting a custom port for UWSGI through the environment while keeping the default port as fallback to keep backwards compatibility.
=> Allow specifying port through LINKDING_PORT environment variable

README.md
Hi @sissbruecker,
Thank you for building and maintaining this awesome tool! 🚀 
I don't know if you find this useful but I built a [helm chart](https://charts.pascaliske.dev/charts/linkding/) for this container for anyone who wants to install it inside an Kubernetes cluster. It would be an honor for me to be mentioned on your project!
Feel free to close this PR if you don't want to mention it! 🙂
=> docs(readme): add community helm chart reference to readme

README.md
I started building a linkding workflow for Alfred and realized that instead of burying the linkding API logic in the workflow, it would be helpful (for both that project and others) to create a Python3, async wrapper library. Thus, this PR adds [`aiolinkding`](https://github.com/bachya/aiolinkding) to the community section of the docs.
=> Add community reference to aiolinkding

bookmarks/services/importer.py, bookmarks/services/parser.py, bookmarks/tests/helpers.py, bookmarks/tests/test_importer.py, bookmarks/tests/test_parser.py, requirements.prod.txt, requirements.txt, siteroot/settings/dev.py
Changes:
- all database operations run in bulk
- replaced parser with an implementation based on `HTMLParser`, adapted from the work in #199 by @jwezel
- when synchronizing an existing bookmark, new tags now are appended instead of replacing the previous ones
Closes #213 
Closes https://github.com/sissbruecker/linkding/issues/155
=> Improve import performance

docs/how-to.md
Change the paraphrasing to the exact name of the correct "Show Web Page At" selection under the Safari category in IOS Shortcuts.
Wow did this confuse me until I figured it out :) Hopefully this helps the next new user! Love this app to bits!
The instructions are very good otherwise. I now have a fully working shortcut.
=> Update how-to.md to fix unclear/paraphrased Safari action in IOS Shortcuts

bookmarks/queries.py, bookmarks/styles/util.scss, bookmarks/templates/bookmarks/archive.html, bookmarks/templates/bookmarks/index.html, bookmarks/tests/test_bookmark_index_view.py, bookmarks/tests/test_queries.py
Closes #192 
Created a Docker image for testing: [`sissbruecker/linkding:search-untagged-bookmarks`](https://hub.docker.com/layers/199660767/sissbruecker/linkding/search-untagged-bookmarks/images/sha256-af91d70e3bfca182812b74c61b0fa8fc6e2b5dbd218dd9a4995ff2fc4f881e93?context=repo)
=> Allow searching for untagged bookmarks

bookmarks/services/website_loader.py
=> Fake request headers to reduce bot detection

bookmarks/api/routes.py, bookmarks/api/serializers.py, bookmarks/tests/test_bookmarks_api.py, docs/API.md
This PR implements a POST method for the `/api/bookmarks/archived` endpoint that creates an archived bookmark directly.
It would be helpful for #243.
=> Add POST archived API endpoint

bookmarks/api/serializers.py, bookmarks/tests/helpers.py, bookmarks/tests/test_bookmarks_api.py
Allows partial updates to bookmarks using the REST API, by making a `PATCH` request to `/api/bookmarks/<id>/`.
Closes #267
=> Add PATCH support to bookmarks endpoint

bookmarks/services/tasks.py, bookmarks/services/website_loader.py, bookmarks/tests/test_bookmarks_tasks.py, requirements.prod.txt, requirements.txt
Fixes https://github.com/sissbruecker/linkding/issues/256
The current version of `waybackpy` is no longer supported. This PR upgrades to the latest with the appropriate changes. A [docker image](https://github.com/dustinblackman/linkding/pkgs/container/linkding/25003411?tag=fix-wayback) is available for quick manual QA.
=> (fix): Wayback machine - Upgrade to 3.0.6

bookmarks/services/bookmarks.py, bookmarks/tests/test_bookmarks_api.py, bookmarks/tests/test_bookmarks_service.py
Fixes the unread flag of bookmarks not being updated when saving a bookmark with a duplicate URL through the form or the API.
=> Update unread flag when saving duplicate URL

docs/API.md
This PR adds small API doc updates to highlight [the new shared bookmark feature](https://github.com/sissbruecker/linkding/pull/311).
=> Add simple docs of the new `shared` API parameter

.env.sample, bookmarks/templates/bookmarks/layout.html, bookmarks/tests/test_context_path.py, bookmarks/urls.py, bookmarks/views/settings.py, docs/Options.md, siteroot/settings/base.py, siteroot/urls.py, uwsgi.ini
add an optional environment variable: LD_CONTEXT_PATH.
I'm not very familiar with django, but I tried my best to do it.
Please let me know if there is any code to improve.
Thank you.
Closes: #127
=> Add support for context path

bookmarks/tests/test_bookmark_edit_view.py, bookmarks/tests/test_bookmark_new_view.py
This test seems to rely on the tags being queried in a specific order from the database, which is incidentally the case for SQLite.
This came up when I was merging my postgres fork with the latest release [here](https://github.com/sissbruecker/linkding/commit/99582f3d45d0c2d54df66113c019c95c75841c1d#diff-fa1abe4b8e2fd558c4c4450b3bd9b5bf0a255cfc516b8d125fcbf7534d7d1efdR41-R43)
=> Order tags in test_should_create_new_bookmark

bookmarks/services/tasks.py, bookmarks/services/wayback.py, bookmarks/templates/settings/general.html, bookmarks/tests/test_bookmarks_tasks.py
The Wayback Machine Save API only allows a limited number of requests within a timespan. This introduces several changes to avoid rate limit errors:
- There will be max. 1 attempt to create a new snapshot
- If a new snapshot could not be created, then attempt to use the latest existing snapshot
- Bulk snapshot updates (bookmark import, load missing snapshots after login) will only attempt to load the latest snapshot instead of creating new ones
=> Prevent rate limit errors in wayback machine API

bookmarks/services/website_loader.py, bookmarks/tests/test_website_loader.py
Limits the size of scraped HTML documents to prevent out of memory errors. The scraper will stop reading from the response when it encounters the closing head tag, or if the read content's size exceeds a max limit.
Fixes #345
=> Limit document size for website scraper

README.md
Also includes a docker-compose example, and minimal vhost configuration.
=> Add apache reverse proxy documentation.

docs/Options.md
Corrects documentation regarding handling of remote users when enabling the `LD_ENABLE_AUTH_PROXY` option.
Closes #372
=> Correct LD_ENABLE_AUTH_PROXY documentation

bookmarks/templates/settings/nav.html
If the user does not have the permissions, there shouldn't be the link to the admin interface.
=> Only show admin link for superusers

bootstrap.sh, uwsgi.ini
Fix for #284. Useful for when running in docker or kubernetes. 
Two things it fixes:
* Signals were not making their way to the `uwsig` process as it was invoked from the `bootstrap.sh` entrypoint script. By `exec`ing that command, it will receive signals. 
* However, in `uwsig` versions before 2.10, it treats `SIGTERM` a bit oddly. [See here](https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html):
> Till uWSGI 2.1, by default, sending the SIGTERM signal to uWSGI means “brutally reload the stack” while the convention is to shut an application down on SIGTERM. To shutdown uWSGI use SIGINT or SIGQUIT instead. If you absolutely can not live with uWSGI being so disrespectful towards SIGTERM, by all means enable the die-on-term option. Fortunately, this bad choice has been fixed in …
=> Gracefully stop docker container when it receives SIGTERM

.env.sample, Dockerfile, README.md, docs/Options.md, requirements.prod.txt, requirements.txt, siteroot/settings/base.py
Allow use postgres as db engine
=> Add postgres as database engine

bookmarks/services/website_loader.py, bookmarks/templates/bookmarks/form.html, bookmarks/tests/test_website_loader.py
Some sites seem to return metadata titles / descriptions with trailing or leading whitespaces, which should be unwanted in most if not all cases. This PR adds a [`.trim`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim) method call to the fetched values, which will remove these whitespaces.
The whitespaces are not shown in the bookmark list after it is saved, but they are being stored, so they are also still there when editing the bookmark.
One example would be [Humble Bundle](https://www.humblebundle.com/) pages, e.g. this one: https://www.humblebundle.com/software/unreal-engine-ultimate-game-dev-assets-software
=> Trim website metadata title and description

bookmarks/services/bookmarks.py, bookmarks/tests/test_bookmarks_service.py
Ensure website metadata is updated when changing the URL of an existing bookmark.
=> Fix bookmark website metadata not being updated when URL changes

bookmarks/services/website_loader.py, bookmarks/tests/test_website_loader.py
Caches results from scraping websites, which allows to skip scraping when saving a bookmark if the URL has already been scraped when opening the bookmark form. This should speed up saving bookmarks a bit.
=> Cache website metadata to avoid duplicate scraping

bookmarks/api/routes.py, bookmarks/templates/bookmarks/form.html, bookmarks/tests/test_bookmarks_api.py
When adding a new bookmark, and if the URL entered into the bookmark form is already bookmarked, prefill the form with the data from the existing bookmark. Saving the bookmark will update the existing bookmark, which works the same as before.
=> Prefill form if URL is already bookmarked

bookmarks/services/tasks.py, bookmarks/tests/test_bookmarks_tasks.py
With the introduction of the favicon background task, adding a bookmark can result in running both, the web archive snapshot task, and the favicon task in parallel. Both load the bookmark at the start of the task, then do their own processing, and then save the bookmark at the end. This could result in one task overriding the updated data of the other task, as the bookmark instance was not refreshed at the end of the task, before saving it. From testing this usually results in the favicon being cleared by the snapshot task, as the snapshot task takes longer.
Refreshing the bookmark would ideally wrap refreshing and saving the bookmark in a transaction, however that sporadically results in database locked errors with Sqlite. Instead this fix involves only updating the field that is …
=> Fix favicon being cleared by web archive snapshot task

bookmarks/services/exporter.py, bookmarks/tests/test_exporter.py
Fixes https://github.com/sissbruecker/linkding/issues/396
=> Escape texts in exported HTML

Dockerfile
When using the context path setting the health check defined in Dockerfile fails, reporting the container state as unhealthy. That's because the path to the health endpoint is hardcoded to `/health` in Dockerfile, while the actual endpoint is provided under `${LD_CONTEXT_PATH}/health`.
This patch changes the path in Dockerfile to honor the value of LD_CONTEXT_PATH.
=> Make health check in Dockerfile honor context path setting

bookmarks/components/TagAutocomplete.svelte, bookmarks/templates/bookmarks/form.html, bookmarks/tests/test_bookmark_edit_view.py
I use lowercase names for all of my tags, so I find it annoying that the first tag I enter defaults to being capitalized (at least on mobile on iOS), and figured I'd open this PR to address it.
This change may be controversial [if others actually prefer this behavior](https://xkcd.com/1172/), but I feel that the current behavior of autocapitalizing only the first tag entered (as if inputting a sentence) is confusing at best.
=> Disable autocapitalization for tag input form

bookmarks/styles/base.scss
This PR adds a media query which sets the font-size for `.form-input` elements to `1rem` on viewports which are `430px` wide or smaller. This aims to prevent the automatic zoom-in on small viewports on iOS devices which slightly zoom-in a website after focusing an input element if the font-size of that element is smaller than 16px.
I am not sure if `base.scss` is the correct place for that change, but since it affects `.form-input` elements on mulitple views (e.g. the login inputs and the search input) that file felt fitting.
=> Prevent zoom-in after focusing an input on small viewports on iOS devices

docs/Options.md, uwsgi.ini
Add a new *LD_LOG_X_FORWARDED_FOR* environment variable allowing to manage 
uWSGI [log-x-forwarded-for](https://uwsgi-docs.readthedocs.io/en/latest/Options.html?#log-x-forwarded-for) parameter. It allows to use the ip from *X-Forwarded-For* header instead of *REMOTE_ADDR* in logs and thus to keep real client IP when using a reverse proxy.
=> Allow to log real client ip in logs when using a reverse proxy

README.md
I notice that for some time the list under Community has not had items added in alphabetical order. 
But I have not reordered any items.
=> Add Postman Collection to Community section of README

.devcontainer/devcontainer.json, .dockerignore, .gitattributes, README.md
For #473 
This adds the necessary files to support developing with Dev Containers. It should have no impact on anyone who chooses to develop without Dev Containers, it simply adds it as an option.
The changes:
* devcontainer.json - The Dev Container configuration. Uses an image with Python 3.10 and NodeJS support added. It also automatically runs several of the necessary commands on creation making it easier for new users
* .gitattributes - Dev Containers appear to have this issue on Windows where the files are checked out with Windows file endings, then loaded into a Linux dev container where it expects different line endings. This resolves that. It should have no impact on anyone else
* readme.md - Added that Dev Containers are supported, and added a link which would automatically check …
=> Added Dev Container support

bookmarks/templates/bookmarks/bookmarklet.js, bookmarks/tests/test_bookmark_new_view.py, bookmarks/views/bookmarks.py
Related to #118 I have made the following changes:
* Updated the New Bookmark page to accept 'title' and 'description' from the URL
* Updated the automated tests for New Bookmark
=> Allow passing title and description to new bookmark form

bookmarks/services/website_loader.py, bookmarks/tests/test_website_loader.py
Removes left-over bytes after end of head to avoid problems with charset detection.
=> Fix website loader content encoding detection

bookmarks/services/favicon_loader.py, bookmarks/services/tasks.py, bookmarks/templates/settings/general.html, bookmarks/tests/test_favicon_loader.py, docs/Options.md, siteroot/settings/base.py
This adds various improvements to how favicons work:
- Changes the default favicon provider to use a higher-resolution image to give better results for high DPI displays
- Adds a `{domain}` placeholder for custom favicon providers that require only the domain / host name without the URL scheme
- Automatically tries to detect the correct file extension for the loaded favicon
- Adds DuckDuckGo as an alternative favicon provider to the documentation
Closes https://github.com/sissbruecker/linkding/issues/465
=> Various improvements to favicons

bookmarks/services/exporter.py, bookmarks/services/importer.py, bookmarks/services/parser.py, bookmarks/templates/settings/general.html, bookmarks/tests/helpers.py, bookmarks/tests/test_exporter.py, bookmarks/tests/test_importer.py, bookmarks/tests/test_parser.py, bookmarks/tests/test_settings_import_view.py, bookmarks/views/settings.py
Adds support for the `PRIVATE` flag when importing / exporting in the Netscape HTML format in order to improve compatibility with other bookmark apps that support marking bookmarks as public / private.
When importing bookmarks, a new option allows to import non private bookmarks (`PRIVATE="0"`) as shared bookmarks. This is opt-in because:
- it keeps the existing default behavior which imports all bookmarks as private
- the export function previously did set `PRIVATE="0"` (=public) on all exported bookmarks, regardless whether they were shared or not
The export has been changed to properly set the `PRIVATE` flag, depending on whether a bookmark is marked as shared or not.
Part of https://github.com/sissbruecker/linkding/issues/484
=> Add support for PRIVATE flag in import and export

bookmarks/e2e/e2e_test_bookmark_page_partial_updates.py, bookmarks/frontend/behaviors/confirm-button.js, bookmarks/styles/base.scss, bookmarks/styles/bookmark-page.scss, bookmarks/templates/bookmarks/bookmark_list.html, bookmarks/templates/bookmarks/layout.html, bookmarks/tests/test_bookmark_action_view.py, bookmarks/tests/test_bookmark_archived_view.py, bookmarks/tests/test_bookmark_index_view.py, bookmarks/tests/test_bookmark_shared_view.py, bookmarks/tests/test_bookmark_shared_view_performance.py, bookmarks/tests/test_bookmarks_list_template.py, bookmarks/views/bookmarks.py, bookmarks/views/partials/contexts.py
Adds a button to the bookmark actions that shows the shared state of the bookmark. Clicking the button brings up a confirmation to unshare the bookmark. For consistency, the mark as read button also has been changed to instead show the state ("Unread"), rather than the action. Clicking that button also brings up a confirmation to mark the bookmark as read.
Closes https://github.com/sissbruecker/linkding/issues/484
=> Display shared state in bookmark list

bookmarks/e2e/e2e_test_bookmark_page_bulk_edit.py, bookmarks/e2e/e2e_test_bookmark_page_partial_updates.py, bookmarks/e2e/helpers.py, bookmarks/frontend/behaviors/bookmark-page.js, bookmarks/frontend/behaviors/bulk-edit.js, bookmarks/frontend/behaviors/tag-autocomplete.js, bookmarks/frontend/components/TagAutocomplete.svelte, bookmarks/services/bookmarks.py, bookmarks/styles/base.scss, bookmarks/styles/bookmark-page.scss, bookmarks/templates/bookmarks/archive.html, bookmarks/templates/bookmarks/bookmark_list.html, bookmarks/templates/bookmarks/bulk_edit/bar.html, bookmarks/templates/bookmarks/index.html, bookmarks/templates/bookmarks/shared.html, bookmarks/tests/helpers.py, bookmarks/tests/test_bookmark_action_view.py, bookmarks/tests/test_bookmark_archived_view.py, bookmarks/tests/test_bookmark_index_view.py, bookmarks/tests/test_bookmark_shared_view.py, bookmarks/tests/test_bookmarks_list_template.py, bookmarks/tests/test_bookmarks_service.py, bookmarks/urls.py, bookmarks/views/bookmarks.py, bookmarks/views/partials/contexts.py
Adds the following bulk edit actions:
- Mark as read
- Mark as unread
- Share
- Unshare
Also adds a toggle that allows bulk editing bookmarks across all pages matching the current query.
Closes https://github.com/sissbruecker/linkding/issues/308
Closes https://github.com/sissbruecker/linkding/issues/208
Closes https://github.com/sissbruecker/linkding/issues/397
=> Allow bulk editing unread and shared state of bookmarks

Dockerfile, bookmarks/signals.py
Allows case-insensitive search for unicode characters (cyrillic, umlauts, ...) when using SQLite.
Fixes https://github.com/sissbruecker/linkding/issues/181
Fixes https://github.com/sissbruecker/linkding/issues/485
=> Fix case-insensitive search for unicode characters in SQLite

siteroot/settings/base.py
#520 introduced a memory leak which is caused by loading an ICU collation into new database connections. Whatever memory is reserved by that is not released when closing the connection, and as each request creates a new connection, memory usage just keeps increasing. As the collation loading is external code I don't see how I could fix that. I also don't want to rollback the fix from #520 as the new sort by title feature relies on that as well. As a workaround, this makes SQLite database connections persistent, so that they are only created once and then reused indefinitely. Hoping that this doesn't cause any other issues.
=> Fix memory leak with SQLite

bookmarks/feeds.py, bookmarks/tests/test_feeds.py
Previously, the 'sanitize' function would throw an error when 'text' was None. This commit fixes the issue by adding a check to handle the case where 'text' is None, returning an empty string instead.
Closes #568
=> Fix RSS feed not handling None values 

bookmarks/management/commands/backup.py, docs/backup.md
Adds a CLI command that allows to create a backup copy of the SQLite database within the Docker container. The file can then be moved to the host system using `docker cp`.
Closes https://github.com/sissbruecker/linkding/issues/454
=> Add backup CLI command

README.md
Add a note that I've created a one-click app for Linkding in CapRover (Scalable PaaS, automated Docker+nginx).
=> Add CapRover as managed hosting option

requirements.txt
I'm using an M1 mac, and without these changes I was unable to install the requirements.txt on my local machine.
=> Bump playwright dependencies

bookmarks/frontend/behaviors/bookmark-page.js, bookmarks/styles/bookmark-page.scss, bookmarks/templates/bookmarks/bookmark_list.html, bookmarks/tests/test_bookmarks_list_template.py
Fixes #606 
This is what it looks like with a custom hover over a link that has an overly long title. 
Light theme.
=> Add title to link so you can see the entire title when hover

bookmarks/management/commands/generate_secret_key.py, bookmarks/templates/bookmarks/form.html, bootstrap.sh, requirements.in, requirements.txt, siteroot/settings/base.py, siteroot/settings/prod.py
Avoid secret key being regenerated when creating new Docker containers, and persist it in the data folder instead. This should avoid forced logins after recreating the container.
Fixes #619
=> Persist secret key in data folder

bookmarks/tests/test_tag_cloud_template.py, bookmarks/views/partials/contexts.py
Fix #588, following the suggestion of using regex to find the ideographic range in this SO answer https://stackoverflow.com/a/2718203/554903
We group the ideographic characters together, while keeping other chinese, japanese and korean characters apart.
(just for the record, I speak japanese).
=> Group ideographic characters in tag cloud

docs/backup.md
The previous directory may not share the same directory as the user that runs the container. `/etc/linkding/data` is a safe directory.
Fixes #626
=> Update backup location to safe directory

docker/alpine.Dockerfile, docker/default.Dockerfile
- Use Node 20 in Debian image, which is the minimum for single-file-cli
- Use forked version of single-file-cli which contains some hotfixes not present in upstream
=> Fix HTML snapshot errors related to single-file-cli

bookmarks/tests/test_oidc_support.py, docs/Options.md, siteroot/settings/base.py
Adds the setting OIDC_VERIFY_SSL which allows to accept ssl certificates from untrusted (e.g. self-signed or created using a custom certificate authority) sources.
Without this setting, every OIDC login attempt fails with:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='auth.example.com', port=443): Max retries exceeded with url: /api/oidc/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))`
=> Add option to disable SSL verification for OIDC

bookmarks/management/commands/backup.py, bookmarks/management/commands/full_backup.py, docs/backup.md
Adds a new `full_backup` CLI command to create a full backup of linkding's data folder. That includes:
- The SQLite database
- The assets folder, which currently only contains HTML snapshots of bookmarked websites
- The favicons folder which contains downloaded favicons
The backup docs have been updated to promote this as the default backup method. The previous `backup` command that only creates a backup of the database has been deprecated.
=> Add full backup method

bookmarks/services/tasks.py, bookmarks/tests/test_bookmarks_tasks.py
Fixes https://github.com/sissbruecker/linkding/issues/681
=> Truncate snapshot filename for long URLs

bookmarks/services/singlefile.py, bookmarks/tests/test_singlefile_service.py, docs/Options.md, siteroot/settings/base.py
Closes #685 
Testing procedure (I did not build & deploy a container):
1. Recreate container with `LD_SINGLEFILE_TIMEOUT_SEC=360` in the compose file. 
2. `docker exec` into the running container, modify `base.py` and `singlefile.py` per below 
3. `docker restart` the container. 
4. Verified that the URL mentioned in above issue worked with a 360 second timeout on Raspberry Pi 4.
=> Add option for customizing single-file timeout

bookmarks/services/singlefile.py, bookmarks/tests/test_singlefile_service.py, docs/Options.md, siteroot/settings/base.py
Closes #690 
Needs some additional testing:
- base.py already looks for LD_SINGLEFILE_OPTIONS and defaults to "" when null; shlex.split("") returns [], so change should work when env variable unset
- Tested with `--user-agent <foo>` and it worked on reddit (see linked issue)
- Needs testing with multiple arguments, e.g. `--user-agent <foo> --block-videos=true --block-audios=true`
=> Add option for passing arguments to single-file command

.gitignore, bookmarks/services/singlefile.py, bookmarks/tests/test_singlefile_service.py, bootstrap.sh, docker/alpine.Dockerfile, docker/default.Dockerfile, scripts/setup-ublock.sh, siteroot/settings/base.py
Integrates the uBlock Origin browser extension with snapshot creation so that it removes ads, as well as cookie banners that might block page scrolling when viewing the snapshot.
=> Remove ads and cookie banners from HTML snapshots

bookmarks/services/tasks.py, bookmarks/templates/settings/general.html, bookmarks/tests/test_bookmarks_tasks.py, bookmarks/tests/test_settings_general_view.py, bookmarks/tests/test_settings_import_view.py, bookmarks/views/settings.py
Adds a button to the settings for creating HTML snapshots for bookmarks that don't have one yet. This is mostly intended to help users migrating from a version of linkding that didn't include the snapshot feature, allowing them to bulk create snapshots for bookmarks added before the migration.
The feature will only create a snapshot if the bookmark doesn't already have a successful or a queued snapshot.
Closes https://github.com/sissbruecker/linkding/issues/676
--- 
---
=> Add button for creating missing HTML snapshots

bookmarks/frontend/behaviors/bookmark-page.js, bookmarks/frontend/behaviors/bulk-edit.js, bookmarks/frontend/behaviors/confirm-button.js, bookmarks/frontend/behaviors/dropdown.js, bookmarks/frontend/behaviors/fetch.js, bookmarks/frontend/behaviors/form.js, bookmarks/frontend/behaviors/global-shortcuts.js, bookmarks/frontend/behaviors/index.js, bookmarks/frontend/behaviors/modal.js, bookmarks/frontend/behaviors/tag-autocomplete.js, bookmarks/templates/bookmarks/details/assets.html, bookmarks/templates/bookmarks/details_modal.html, bookmarks/tests/test_bookmark_details_modal.py, bookmarks/urls.py, bookmarks/views/bookmarks.py, bookmarks/views/partials/contexts.py, web-types.json
Live updates the file list in the bookmark details modal when there is a queued HTML snapshot. Thus, when the snapshot eventually completes the UI will update and show it as such. Also disables the create snapshot button when there already is a queued snapshot.
Closes https://github.com/sissbruecker/linkding/issues/673
=> Refresh file list when there are queued snapshots

docker/alpine.Dockerfile, docker/default.Dockerfile, scripts/setup-ublock.sh
Remove remote URLs from uBlock configuration so that it doesn't override its modified configuration on startup.
=> Make blocking cookie banners more reliable

bookmarks/admin.py, bookmarks/models.py
When viewing the detail of a BookmarkAsset in the admin panel, it shows as the default object string.
I have added a very basic string method, which uses the display_name or if that is not present (as its not mandatory), defaults to a simple string.
**With no display_name**
**With display_name**
This is also reflected on the list page also
=> Show proper name for bookmark assets in admin

bookmarks/static/vendor/Readability.js, bookmarks/styles/reader-mode.scss, bookmarks/styles/theme-dark.scss, bookmarks/styles/theme-light.scss, bookmarks/templates/bookmarks/details/assets.html, bookmarks/templates/bookmarks/details/form.html, bookmarks/templates/bookmarks/read.html, bookmarks/tests/test_bookmark_asset_view.py, bookmarks/tests/test_bookmark_details_modal.py, bookmarks/urls.py, bookmarks/views/assets.py, bookmarks/views/partials/contexts.py
Adds a reader mode view for bookmarks. This uses Mozilla readability to convert the HTML captured from a snapshot into a readable representation. That also means the feature requires snapshots, and is only available in the `latest-plus` image. Likewise, the reader mode link will only show up once there is a successful snapshot.
Closes https://github.com/sissbruecker/linkding/issues/286
---
=> Add reader mode

bookmarks/frontend/behaviors/form.js, bookmarks/models.py, bookmarks/services/bookmarks.py, bookmarks/styles/bookmark-details.scss, bookmarks/templates/bookmarks/details/assets.html, bookmarks/tests/test_bookmark_details_modal.py, bookmarks/tests/test_bookmarks_service.py, bookmarks/views/bookmarks.py, web-types.json
Allows to upload custom files for each bookmark. That allows storing any arbitrary data (PDFs, images, text files, ...) that is related to that bookmark. Could also be used to store custom snapshots of a website in case the automated HTML snapshot does not work properly.
=> Allow uploading custom files for bookmarks

bookmarks/styles/bookmark-page.scss
If you click on a link on mobile (I tried on iOS), then go back, the link will be in focus and the tooltip will overlap half of the link, which is annoying because it's hard to take the focus off on mobile.
=> Hide tooltip on mobile

bookmarks/templates/bookmarks/bookmark_list.html
Prefer IntersectionObserver over loading=lazy because Safari still loads images when loading=lazy
=> Thumbnails lazy loading

README.md
Pinkt is a well established Android app which serves as an unofficial client for Pinboard for over 5 years. [Version 3.0](https://github.com/fibelatti/pinboard-kotlin/releases/tag/v3.0) has finally introduced support for Linkding and most of its features, and the app is now ready to be used as an unofficial client for Linkding too.
=> Add Pinkt to the Community section

docker-compose.yml
Removing version line from docker compose. This line is now obsolete and will throw a warning when starting the docker compose stack.
=> removed version line from docker compose yaml

siteroot/settings/base.py
I noticed that the time zone wasn't set up right for me, and eventually came across [this](https://github.com/sissbruecker/linkding/issues/179#issuecomment-986292357) which got me up and running.
However, both that issue and [this more recent one](https://github.com/sissbruecker/linkding/issues/764) were opened by people trying to use the standard docker `TZ` var to set the app time zone. That seems like a reasonable thing to do.
If you agree, what do you think of this small fix?
> [!NOTE]
> An alternate approach might be to use the system time zone instead of UTC as the default. That would give the benefit of working for both bare metal installs as well as docker containers configured with `TZ`.
Closes https://github.com/sissbruecker/linkding/issues/764
=> Allow use of standard docker `TZ` env var

docker/alpine.Dockerfile, docker/default.Dockerfile
This commit adds the `org.opencontainers.image.source` label to the built container images.
This label is helpful for tools to be able to link back from the container image to the source repo.
For example, for those that use Renovate to help auto update dependencies, this will result in the latest releases release notes/changelog being included in the PR which is very handy!
=> Add OCI source annotation to link back to source repo

bookmarks/models.py, bookmarks/tests/test_bookmark_new_view.py, bookmarks/views/bookmarks.py
Closes https://github.com/sissbruecker/linkding/issues/779
=> Allow pre-filling notes in new bookmark form

bookmarks/api/routes.py, bookmarks/services/auto_tagging.py, bookmarks/services/bookmarks.py, bookmarks/tests/test_auto_tagging.py
Fixes https://github.com/sissbruecker/linkding/issues/815
=> Fix auto-tagging when URL includes port

bookmarks/services/singlefile.py, bookmarks/tests/test_bookmarks_tasks.py, bookmarks/tests/test_singlefile_service.py
=> Rename "SingeFileError" to "SingleFileError"

.env.sample, bootstrap.sh, docs/Options.md
I've been wanting to start using linkding and installed it into my Kubernetes cluster, but couldn't access it.
My cluster runs only using IPv6 addresses and I noticed that the default configuration for uWSGI that is used in this project, defaults to binding only to an IPv4 socket and there is no config option to change this behaviour.
In the current year, with IPv4 addresses becoming more scarce and often an addon that needs to be paid extra, I think it's reasonable to change the default to **also** allow for IPv6 connections.
**This does not break any existing configurations**, as this creates a dual stack socket, which will respond to requests on both protocols (IPv4 addresses are displayed as IPv4-mapped IPv6 addresses and look like this: "::ffff:x.x.x.x".
Yet I have also provided a …
=> Implement IPv6 capability

docs/src/content/docs/community.md
Hi. First of all, thanks for the work on linkding. I've developed [go-linkding](https://github.com/piero-vic/go-linkding), a go library to interact with the API. I'm in the process of adding some tests that run against the docker container to ensure the library is always compatible with the latest version of linkding. I'm already using it in a couple of projects. Hope the community can make good use of it.
=> Add go-linkding to community projects

requirements.txt
This avoids the yanked 3.23.0 version and allows pip-compile to work without --upgrade again.
Fixes #838
=> Bump requests version to 3.23.3

bookmarks/templates/settings/general.html
This fixes a broken link on the settings page to lead to the website's documentation
=> Fix a broken link to options documentation

bookmarks/tests/test_login_view.py, siteroot/urls.py
Failed login attempts now return a `401` status code, resulting in uwsgi logs like:
```
2024-09-23 14:12:50,557 WARNING Unauthorized: /login/
[pid: 20|app: 0|req: 3/9] ::ffff:192.168.65.1 () {54 vars in 1728 bytes} [Mon Sep 23 14:12:50 2024] POST /login/ => generated 5956 bytes in 276 msecs (HTTP/1.1 401) 11 headers in 519 bytes (1 switches on core 1)
```
Closes https://github.com/sissbruecker/linkding/issues/489
=> Add basic fail2ban support

bookmarks/api/serializers.py, bookmarks/services/bookmarks.py, bookmarks/tests/test_bookmarks_api.py, bookmarks/tests/test_bookmarks_api_permissions.py, docs/src/content/docs/api.md
Previously, `POST` requests to the API would reset fields that are not provided in the request to their default values. While documented, the behavior was sort of accidental and potentially dangerous when new fields get added. Thus a small behavior change to not modify fields that are not part of the request.
=> Do not clear fields in POST requests (API behavior change)

bookmarks/api/serializers.py, bookmarks/models.py, bookmarks/tests/test_bookmark_edit_view.py, bookmarks/tests/test_bookmarks_api.py, docs/src/content/docs/api.md
Returns a validation error when trying to edit a bookmark to use a URL that is already used by a different bookmark.
When creating a bookmark with a duplicate URL it will still update the existing bookmark instead, same as before.
=> Prevent duplicates when editing

.gitignore, bookmarks/tests/test_singlefile_service.py, docker/alpine.Dockerfile, docker/default.Dockerfile, scripts/setup-ublock.sh, siteroot/settings/base.py
uBlock Origin does not work anymore in latest Chrome / Chromium versions due to the removal of the Manifest V2 extension API. The linkding `latest-plus-alpine` image is already affected by this in that the extension doesn't load anymore, causing HTML snapshots to fail. The Debian image will also be affected once they upgrade to a more recent Chrome version.
This replaces uBlock Origin with uBlock Origin Lite which does work with newer Chromium versions.
Fixes https://github.com/sissbruecker/linkding/issues/864
=> Replace uBlock Origin with uBlock Origin Lite

docs/src/content/docs/options.md, uwsgi.ini
=> Add option to disable request logs

bookmarks/static/robots.txt, uwsgi.ini
Adds a default robots.txt that instructs crawlers to not index the application. To customize this, a custom robots.txt could be mounted into the Docker container at `/etc/linkding/static/robots.txt`.
Closes https://github.com/sissbruecker/linkding/issues/956
=> Add default robots.txt to block crawlers

bookmarks/tests/test_oidc_support.py, bookmarks/utils.py, docs/src/content/docs/options.md, siteroot/settings/base.py
Fixes #793
Allow config of oidc claim used for username generation (default to email claim to avoid breaking existing installs)
=> Allow customizing username when creating user through OIDC

bookmarks/models.py, bookmarks/tests/test_bookmark_assets.py, bookmarks/tests/test_bookmark_previews.py
Fixes https://github.com/sissbruecker/linkding/issues/883
=> Remove preview image when bookmark is deleted

docs/src/content/docs/options.md
Resolves #988
There were a number of trailing whitespace characters in the doc, I removed those as well.
=> Add note about OIDC and LD_SUPERUSER_NAME combination

bookmarks/api/routes.py, bookmarks/api/serializers.py, bookmarks/services/assets.py, bookmarks/services/bookmarks.py, bookmarks/services/singlefile.py, bookmarks/services/tasks.py, bookmarks/templates/bookmarks/details/assets.html, bookmarks/templates/bookmarks/details/form.html, bookmarks/tests/test_assets_service.py, bookmarks/tests/test_bookmark_action_view.py, bookmarks/tests/test_bookmark_details_modal.py, bookmarks/tests/test_bookmarks_api.py, bookmarks/tests/test_bookmarks_api_permissions.py, bookmarks/tests/test_bookmarks_service.py, bookmarks/tests/test_bookmarks_tasks.py, bookmarks/tests/test_singlefile_service.py, bookmarks/views/bookmarks.py, bookmarks/views/contexts.py
Part of https://github.com/sissbruecker/linkding/issues/980
=> Add REST endpoint for uploading snapshots from the Singlefile extension

docs/src/content/docs/community.md
Adding android client linklater to community projects md. Fixes #741
=> Adding linklater to community projects

bookmarks/settings/base.py
Closes #1012. With this change, `LD_ENABLE_AUTH_PROXY: True` and `- LD_ENABLE_AUTH_PROXY=True` will both work as expected.
I considered making the check fully case-insensitive, but I figure odd casing like `tRuE` is more likely an error than not.
=> Handle lowercase "true" in environment variables

.github/workflows/build.yaml
This PR updates the GitHub Actions workflow to push Docker images to **GitHub Container Registry (GHCR)** alongside **Docker Hub**.
- Added a Login to GHCR step using `${{ github.token }}`.
- Updated all Docker build steps to include GHCR tags (`ghcr.io/sissbruecker/linkding`).
- Provides an additional registry for hosting images.
- GHCR offers better integration with GitHub (e.g., private repos, organization access).
- Docker Hub usage limits:
- Starting April 1, 2025, unauthenticated users will be limited to 10 pulls/hour, and free authenticated users to 100 pulls/hour.
- Users with Pro, Team, or Business subscriptions will have unlimited pulls with fair use.
- Providing an alternative registry ensures users can still access images without hitting rate limits.
- Workflow should …
=> Push Docker images to GHCR in addition to Docker Hub

bookmarks/templatetags/shared.py, bookmarks/tests/test_bookmarks_list_template.py
Linkifies plain URLs in notes so one does not need to use Markdown syntax to be able to click on links.
At first, I considered using a Python-Markdown extension with Django’s `Urlizer`, but since we already use Bleach, it’s probably easiest to just use it for linkifying as well.
Closes #743.
=> Linkify plain URLs in notes

bookmarks/forms.py, bookmarks/tests/test_bookmark_new_view.py
Hi there 👋 
I'm moving from another comparable system to linkding and realized that I can't set the bookmarks in custom bookmark snippets. This PR reads `tag_string` from the GET requests, allowing to pre-fill tags.
Hope that is ok to add it like I've done in the PR. Let me know if there's also some documentation that needs to be amended.
/dasrecht
=> Allow pre-filling tags in new bookmark form

bookmarks/services/assets.py, bookmarks/tests/helpers.py, bookmarks/tests/test_assets_service.py, bookmarks/tests/test_bookmark_assets_api.py
This adds the feature where files that are uploaded get gzip compressed to save space (and so they are similar to saved SingleFile snapshots).
=> Automatically compress uploads with gzip

docs/src/content/docs/community.md
Updates the community page to include a link to [Pocket2Linkding](https://github.com/hkclark/Pocket2Linkding/).  With Mozilla Pocket shutting down on July 8, 2025 (the export service will be available through Oct 8, 2025), this could be a helpful tool for people looking to find a "home" after Pocket is dead.
=> Add Pocket migration to to community page

bookmarks/services/bookmarks.py, bookmarks/templates/bookmarks/bulk_edit/bar.html, bookmarks/tests/test_bookmark_archived_view.py, bookmarks/tests/test_bookmark_index_view.py, bookmarks/tests/test_bookmarks_service.py, bookmarks/views/bookmarks.py, bookmarks/views/contexts.py
Closes https://github.com/sissbruecker/linkding/issues/869
=> Bulk create HTML snapshots

docs/src/content/docs/api.md
It's possible to filter bookmarks in the API by providing a bundle id, but this is not mentioned in the docs.
=> Document API bundle filter

docs/src/content/docs/community.md
Adds my linkding Bookmarks [Alfred](https://www.alfredapp.com/) workflow to the community docs page. Also fixes a typo with another recent entry on the same page.
=> Add alfred-linkding-bookmarks to community.md

bookmarks/templatetags/pagination.py, bookmarks/tests/test_pagination_tag.py
When I run the application in docker container and access it behind reverse proxy, I see all pagination links point to "localhost:8000" . 
This change fixes the absolute paths to relative (without host and port).
=> Fix pagination links to use relative URLs
